swipe:
  4:
    up:
      command: 'xdotool key Ctrl+F8'
    down:
      #command: 'xdotool key Super+d' # Default one, doesn't need any extra config
      command: 'xdotool key Alt+Shift+d' # Needs to have "Minimize All Windows" widget, with the associated shortcut
    
    left:
      command: 'xdotool key Ctrl+Super+Right'
    right:
      command: 'xdotool key Ctrl+Super+Left'

  3:
    up:
      command: 'xdotool key Ctrl+F9'
    down:
      command: 'xdotool key Alt+Shift+d'

pinch:
  2:
    in:
      command: 'xdotool key Ctrl+Super+Up'
    out:
      command: 'xdotool key ctrl+Super+Down'

threshold:
  swipe: 0.75
  pinch: 0.75

interval:
  swipe: 0.75
  pinch: 0.75
